### ISSUE TITLE
QNAME minimization

### ISSUE THREAD

**Issue by vcunat** [shuque/ns-revalidation#1]
This is more of a nitpick at this point, so let me just file it as an issue.

> [QNAME minimization] would provide a way to definitively learn the child zone's authoritative NS RRset.

I disagree with that.  The RFC 7816 proposes to ask NS one label below apex, not on the apex itself:
> the QNAME that is the original QNAME, stripped to just one label more than the zone for which the server is authoritative

**Comment by shuque** [comment]
Ah, I think I was remembering earlier discussion about NS queries during the development of that document. Thank you. I will update the draft.
